CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE tasks(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    is_complete BOOLEAN DEFAULT FALSE,
    create_at VARCHAR(255) NOT NULL,
    user_id INT REFERENCES users(id) ON DELETE CASCADE
);